[build]
command = “npm run build”
publish = “dist”

# Environment variables that should be available during build

[build.environment]
CI = “false”
NODE_VERSION = “18”

# SPA routing support - redirect all routes to index.html

[[redirects]]
from = “/*”
to = “/index.html”
status = 200

# Headers for better caching and security

[[headers]]
for = “/*”
[headers.values]
X-Frame-Options = “DENY”
X-XSS-Protection = “1; mode=block”

[[headers]]
for = “/static/*”
[headers.values]
Cache-Control = “public, max-age=31536000, immutable”
